- http/request.go
> fix(mispell): correct typos

- .github/workflows/release.yml
- .goreleaser.yml
Adds github action and config for goreleaser.
> feat(goreleaser): add config and actions

- runner/run.go
Fixes not getting to the proper check status with the answer of the web server.
> fix(check): fix expected error check

- README.md
> docs: add more examples on running tests

- README.md
> docs(nginx): add nginx timeformat

- check/base_test.go
- check/error.go
- check/error_test.go
- check/logs.go
- check/logs_test.go
- check/response.go
- check/response_test.go
- check/status_test.go
- main.go
- runner/run.go
- runner/run_test.go
- runner/stats.go
- test/defaults.go
- waflog/waflog_test.go
- Fixed a bug in the tests order
- Add initial support for nginx logs
- Add more integration tests
> fix(nginx): reorder checks and fix some bugs

- README.md
> docs: update time formats in readme

- waflog/read.go
Adding timezone to the parsing also.
> Added the correct timezone to parsing of dates

- README.md
> feat(badge): add LGTM

- .github/workflows/test.yml
> feat(ci): add Go tests in CI

- .pre-commit-config.yaml
- go.mod
- go.sum
- http/request_test.go
- runner/run.go
- runner/run_test.go
- test/files_test.go
- utils/tests_test.go
> improvement(test): adds coverage

- .github/workflows/release.yml
- .github/workflows/test.yml
- sonar-project.properties
- update release to go 1.16
- adds support for sonarcloud quality scanning
> Update golang 1.16

- README.md
> ci(sonarcloud): add new coverage and quality badges

- check/response.go
- check/status.go
- cmd/check.go
- config/init.go
- http/connection.go
- http/request.go
- runner/run.go
- test/files.go
- waflog/read.go
> feat(debug): only show http message in debug mode. to see all use trace

- .pre-commit-config.yaml
- README.md
- check/base.go
- check/base_test.go
- check/logs_test.go
- cmd/run.go
- config/config.go
- config/config_test.go
- config/types.go
- ftwhttp/client_test.go
- ftwhttp/request.go
- go.mod
- go.sum
- runner/run.go
- runner/run_test.go
- runner/stats.go
- runner/types.go
- test/files.go
- test/types.go
- waflog/read.go
- waflog/read_test.go
- waflog/types.go
> Log markers

- runner/run.go
Fixes two bugs with latest merge.
> fix(run): fix handling runner reponse errors

- .github/workflows/sonar.yaml
- .github/workflows/test.yml
Trying to split actions so sonar works for forked repos.
> feat(ci): split actions for sonar

- cmd/check.go
- cmd/root.go
- ftwhttp/client_test.go
- ftwhttp/request.go
- main.go
- runner/run.go
- test/data.go
- waflog/read.go
- waflog/waflog.go
While it'll be good to add lint, in the meantime it'd be good to get the files to reformat to reduce noise in PRs like #69. Though it looks like I already touched a lot of the files 😂
> Reformat code

- README.md
> chore: make testing rule more generic for different waf implementations

- README.md
- cmd/root.go
- cmd/run.go
- config/types.go
Small PR that updates some outdated information inside the readme and the help command
> chore: Updates readme/help

- ftwhttp/client.go
- ftwhttp/client_test.go
- ftwhttp/connection.go
- ftwhttp/rtt.go
- ftwhttp/types.go
- runner/run.go
> Revert "fix: remove RTT tracking from client/transport in favor of direct tra…"

- .pre-commit-config.yaml
- README.md
- check/base.go
- check/base_test.go
- check/error_test.go
- check/logs_test.go
- check/response_test.go
- check/status_test.go
- cmd/check.go
- cmd/root.go
- cmd/run.go
- config/config_test.go
- config/types.go
- ftwhttp/request.go
- go.mod
- main.go
- runner/run.go
- runner/run_test.go
- runner/types.go
- sonar-project.properties
- test/defaults.go
- test/defaults_test.go
- test/errors_test.go
- test/files_test.go
- test/types.go
- waflog/read.go
- waflog/read_test.go
- waflog/waflog.go
- waflog/waflog_test.go
> chore: 🚀 to coreruleset organization

- check/base_test.go
- check/error_test.go
- check/logs_test.go
- check/response_test.go
- check/status_test.go
- config/config_test.go
- ftwhttp/client_test.go
- ftwhttp/connection_test.go
- ftwhttp/header_test.go
- ftwhttp/request_test.go
- ftwhttp/response_test.go
- go.mod
- runner/run_test.go
- test/data_test.go
- test/defaults_test.go
- test/errors_test.go
- test/files_test.go
- utils/empty_test.go
- utils/tests_test.go
- utils/time_test.go
- waflog/read_test.go
- waflog/waflog_test.go
In the spirit of getting better coverage, this PR migrates tests to testify.
- move tests to testify
- achieve coverage > 80%
> test: enhance general coverage

- .github/workflows/codeql-analysis.yml
- .github/workflows/sonar.yaml
- .github/workflows/test.yml
- add tests to develop branch also.
> ci: add branch develop

- README.md
Hi there!
Smallest PR ever. It proposes to fix a couple of code blocks that are currently not correctly rendered.
Cheers!
> chore: fix readme code blocks

- .goreleaser.yml
Let everyone know that a new release is out.
> feat(ci): add slack message when a new release is out

- .github/workflows/release.yml
- add needed token to CI action.
> fix(ci): add env var with token

- README.md
- cmd/run.go
- config/config.go
- config/config_test.go
- config/types.go
- runner/run.go
- runner/types.go
> feat(config): add default max marker as default values

- README.md
> docs: add usage as library

- README.md
Accompanies https://github.com/coreruleset/modsecurity-crs-docker/pull/119
> chore: update documentation of test request rule

- .goreleaser.yml
Fixes goreleaser indentation errors.
> fix: goreleaser slack template

- .github/dependabot.yml
Add dependabot for upgrading dependencies.
> chore(ci): create dependabot for dependency updating

- .github/workflows/scorecard.yml
- add best practices to pipeline
> chore: create scorecard.yml

- README.md
> docs: remove lgtm badge

- renovate.json
Update to new format.
Fixes #282.
> fix: update renovate.json

- renovate.json
> fix: renovate json

- README.md
I went all over the openssf badge process, so we might add the badge here.
> chore: add OpenSSF badge

- check/logs.go
- check/logs_test.go
- go.mod
- go.sum
- runner/run.go
- runner/run_test.go
> Implement isolated

- renovate.json
Needs https://github.com/coreruleset/renovate-config/pull/2
> chore: add renovate approval bot

- cmd/quantitative.go
- go.mod
- go.sum
- internal/quantitative/local_engine.go
- internal/quantitative/runner.go
- internal/quantitative/stats.go
- internal/quantitative/stats_test.go
- magefile.go
- add parallel calls to the coraza engine
- speed! 🏎️
> feat: add parallel run to quantitative testing

- internal/quantitative/runner_test.go
> fix: quantitative test

- go.mod
Reverts coreruleset/go-ftw#402
> Revert "chore(deps): update dependency go to v1.23.3 in go.mod"

- go.mod
- go.sum
Complete removal of raw request.
> chore: update schema to v2.2.0

- check/base.go
- cmd/run.go
- runner/run.go
- runner/run_test.go
- runner/stats.go
- runner/testdata/TestTriggeredRules.yaml
- runner/types.go
- waflog/read.go
Adds list of triggered rules by stage to the JSON output.
Fixes #429
> feat: report triggered rules for every test

- cmd/run.go
- cmd/run_test.go
- expose `--glob` / `-g` to allow users to override the default filename glob
- improve default filename glob to match both `*.yaml` and `*.yml`
> feat: parameterize test file matching
