check/logs.go, http/base.go, main.go, waflog/base.go, waflog/read.go, waflog/waflog_test.go
Add some refactor so we don't use the config in waflog, just inject it using loglines.
=> feat: refactor waflog and add checks

http/header.go, http/header_test.go
Testing sometimes showed in different order. So we sort headers now before writing.
=> fix(header): sort headers by name to get consistent test results

runner/run.go, runner/run_test.go, runner/stats.go
Solves #7.
Now when running with `--quiet`, what you get is just the information about the config file used, and exit codes.
Exit code `0` means all tests good, and `1` test failed with error.
=> feat(quiet): be real quiet on output

README.md, check/base.go, check/base_test.go, check/logs.go, config/config.go, config/config_test.go, config/init.go, waflog/base.go, waflog/read.go
ModSecurity logs in nginx will be without microsecond, so we need to compare the same times when reading logs. Adding `timetruncate` allows you to do exactly that.
=> Fix nginx time comparision

README.md, cmd/check.go, test/files.go, test/files_test.go
Print failed file in check mode.
=> fix(check): print error about failing files now

README.md, check/base.go, check/base_test.go, cmd/root.go, cmd/run.go, config/config.go, config/config_test.go, http/response_test.go, runner/run.go, runner/stats.go, waflog/base.go, waflog/read.go
- Allows tests to be overriden by using a map of `test_id`, `text`.
- Added a new config setting to truncate logs
=> feat(tests): add test result overrides

cmd/root.go, cmd/run.go, runner/run.go, runner/run_test.go
This one fixes error output even when tests were succesful
=> fix(core): change returning as Go err to using os.Exit instead

go.mod, go.sum, http/client.go, http/connection.go, http/request.go, http/response_test.go, http/types.go, runner/run.go
This PR add the last remaining part for compatibility with `ftw`: cookies.
While they are not used actively in the `coreruleset` tests, they are part of `ftw`, so we needed to cover that.
Cookies needed to be integrated at a higher level than connections with the tested waf. They are part of the HTTP client, and need to be active while we run all tests. That way when a server sends any cookie back, the client can add the cookies to the request.
=> feat(cookies): add cookie support

config/config.go, config/config_test.go, runner/run.go, runner/run_test.go
- allows you to override all tests host and port
First part for #42.
=> feat(override): adds feature for everriding host and port globally

cmd/root.go
Add also a new `--cloud` para to easily set cloud mode.
=> feat(cloud): add also cli param to use cloud mode

.editorconfig, .goreleaser.yml, ftwhttp/client.go, ftwhttp/client_test.go, ftwhttp/connection.go, ftwhttp/connection_test.go, ftwhttp/header.go, ftwhttp/header_test.go, ftwhttp/request.go, ftwhttp/request_test.go, ftwhttp/response.go, ftwhttp/response_test.go, ftwhttp/rtt.go, ftwhttp/types.go, runner/run.go, runner/run_test.go, test/defaults_test.go, test/types.go
- Rename http to ftwhttp to avoid collision with base namespace
- Add editorconfig
- Extend goreleaser config to match RC versions.
=> fix(namespace): avoid collision with base http

ftwhttp/client_test.go, ftwhttp/request.go, ftwhttp/request_test.go
=> fix(request): fix data request parsing

runner/run.go, runner/run_test.go, test/files.go
Fixed issues with false positive test results
=> Use the local test web server for all tests

check/base.go, check/base_test.go, cmd/root.go, config/config.go, config/config_test.go, config/types.go, runner/run.go, runner/run_test.go, runner/types.go, waflog/read.go, waflog/read_test.go, waflog/types.go, waflog/waflog.go, waflog/waflog_test.go
Use File.Seek() to move to end of file for next read
=> Only print skip message for disabled tests

runner/run.go, runner/run_test.go
Hi there!
Running the CRS, I bumped into some `SIGSEGV: segmentation violation` because my config has a port override specification, but some rules do not populate the `port:` field. It leads to a nil pointer error, trying to override a not existing value.
- Example of rule that led to a crash: [913120-2](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/tests/regression/tests/REQUEST-913-SCANNER-DETECTION/913120.yaml#L29-L42)
- Snippet of `.ftw.yaml`:
```
testoverride:
input:
port: '80'
```
- Crash output example:
```
$ go run github.com/fzipi/go-ftw@448ecfb02d0128a04ccde3bb601797f7f19eda3f run -d crs-regression-test-v3.3.2/tests/ -i 913120 -t
9:07AM INF 🛠️  Starting tests!
9:07AM INF Integer node found where ArrayNode is expected
🚀 Running go-ftw!
👉 executing tests in file …
```
=> fix: override port with missing port inside test.

runner/run.go
Hi!
Super small PR just to propose some output improvements when `testoverride` is in place.
As far as I understand, overridden tests are not going to be anymore executed, but directly [skipped here](https://github.com/fzipi/go-ftw/blob/main/runner/run.go#L105-L108). So the [`case Ignored:`](https://github.com/fzipi/go-ftw/blob/main/runner/run.go#L259-L260) of the `displayResult` is never going to be executed.
This PR runs `displayResult` also when tests are skipped and adds `ForceFail` and `ForcePass` cases.
Before:
```
👉 executing tests in file 911100.yaml
running 911100-1:   running 911100-2: ✔ passed in 22.314279ms (RTT 95ns)
running 911100-3:   running 911100-4:   running 911100-5: ✔ passed in 21.243191ms (RTT 114ns)
running 911100-6: ✔ passed in 21.226411ms (RTT 83ns)
running …
```
=> chore: improving output for overridden tests

config/config.go, config/config_test.go, config/types.go, runner/run.go, runner/run_test.go, test/types.go
- "Host" header should be overridden with value of `dest_addr` override
to ensure that requests will be accepted by targets.
- Added test for the above change.
- Converted `config.FTWConfig.TestOverride.Input` from `map[string]string`
to `test.Input` for improved validation and better parsing
Co-authored-by: @dkegel-fastly
Replaces #61 
Fixes #60
=> feat: set "Host" header from dest_addr override

README.md
Update README to get all new features.
Fixes #59.
=> docs: Update README will all new features

runner/run.go
Also simplifies messages a bit
=> chore: wrap original error in markAndFlush requests

ftwhttp/client.go
I randomly noticed this while debugging flakiness in my ftw tests. It didn't actually help 😂 But though it's still generally a good idea to close connections since otherwise I guess it is relying on GC.
=> fix: close previous connection before starting new one

cmd/run.go, ftwhttp/client.go, ftwhttp/client_test.go, ftwhttp/connection.go, ftwhttp/response_test.go, ftwhttp/types.go, runner/run.go, runner/run_test.go, runner/types.go
The 1s timeout is pretty long but currently my ftw tests don't pass with it - I need to debug whether this is an Envoy configuration issue, wasm performance issue, whether it affects real traffic, etc, and hopefully it won't be slow. But in the meantime, being able to run the test suite by configuring a higher timeout would be really great.
It looks like some files weren't gofmt'd and my IDE automatically does it, I hope that's OK
=> feat: make request timeout configurable

runner/run.go
The root URI is not mapped by `httpbin`, so the repsponse will contain a large amount of HTML for the 404 page, which ends up in the log. We now use the `/status` endpoint to reduce the data transferred in each response to a marker request and the amount of data in the log.
=> feat: Use httpbin `/status` endpoint for markers

ftwhttp/client.go, ftwhttp/client_test.go, runner/run.go
Marker requests would reset the `Transport` struct, thereby unintentionally resetting the round trip time.
- Add `NewOrReusedConnection` to allow connections to be reused
- Move dialling logic to separate method
- Make marker requests use `NewOrReusedConnection` instead of `NewConnection`
This is an alternative to #76. @fzipi you need to decide which one you want to keep.
=> fix: Reuse connection transport for marker requests

.goreleaser.yml
=> chore: fix goreleaser url homepage after migration

.github/workflows/sonar.yaml, .github/workflows/test.yml, sonar-project.properties
The sonar workflow has always been failing because it attempts to download an artifact uploaded from a different workflow - artifacts are scoped to builds so different workflows can't access them like that. From what I can tell, processing coverage with sonar is to show coverage report in sonarqube. Instead we should upload to codecov so it's open, and I can add that separately if this makes sense.
I also removed running Sonar on pull request because it won't work for PRs from forked repos due to the use of a secret - generally we can't run checks that require secrets on PRs in OSS projects so best to just fix forward if main fails.
=> fix: simplify sonar workflow and only run on push

.goreleaser.yml
This is just style so no worries if not going with this. I want to propose using goreleaser default naming scheme for release archives. goreleaser is very common now, and I like the consistency of archive names I see across various projects when writing tooling. I think it's worth doing that here.
Also publishes a windows-amd64 build (not arm64 since there is no viable platform for that yet)
=> feat: use goreleaser default naming for published archives

README.md
Small fixes in README:
- move logfile section after waf server
- correct path assuming user is relative to coreruleset directory
Fixes #93.
=> docs: small fixed on README

check/base.go, ftwhttp/request.go, ftwhttp/request_test.go
While doing tests using unencoded data, we figured out that some parts of the encoding were not working.
This PR fixes this problem.
=> fix: properly URL encode data for POST requests

cmd/run.go, ftwhttp/client.go, ftwhttp/client_test.go, ftwhttp/connection.go, ftwhttp/response_test.go, runner/run.go, runner/run_test.go, waflog/read.go, waflog/read_test.go, waflog/waflog.go, waflog/waflog_test.go
go-ftw provides a programmatic entry point for tests like this one
https://github.com/corazawaf/coraza/blob/v3/dev/testing/coreruleset/coreruleset_test.go#L213
There are some quirks like global config (will look at in another PR) and the code causing the process to exit because of use of `log.Fatal`, making test failures difficult to understand. This replaces `log.Fatal` with propagating errors. There is one remaining Fatal for a regexp which will require some less mechanical change but that also should have lower chance of triggering
=> fix: remove most uses of log.Fatal when running programatically

.github/workflows/release.yml
- setup buildx before calling goreleaser
=> ci: setup buildx for release docker builds

.github/workflows/codeql-analysis.yml, .github/workflows/release.yml, .github/workflows/sonar.yaml, .github/workflows/test.yml, check/base.go, cmd/run.go, config/config.go, ftwhttp/client.go, ftwhttp/client_test.go, ftwhttp/connection.go, ftwhttp/request.go, ftwhttp/request_test.go, ftwhttp/response_test.go, main.go, runner/run.go, runner/run_test.go, waflog/read.go, waflog/read_test.go, waflog/waflog.go, waflog/waflog_test.go
- ci: setup buildx for release docker builds
- fix: remove most uses of log.Fatal when running (#99)
- fix: remove obsolete use of tzdata (#95)
- fix: properly URL encode data for POST requests (#96)
- ci: add branch develop (#97)
- feature: look for ~/.ftw.yaml after looking in local folder
=> chore: push changes to main

ftwhttp/request.go, ftwhttp/request_test.go
When trying to update FTW, I noticed CRS tests failing and AFAICT, it is because of the escaping behavior introduced in #96. Now, there are never key/value pairs since equals and ampersands are always escaped. Ideally, the test format itself was a yaml map instead of a single string or the single string was always escaped, but as is now, I think we have to assume that `=` and `&` in the `data` field are the form parameter delimiters and only escape the actual key/values.
=> fix: only escape key/values for data in POST requests.

README.md, cmd/run.go, runner/run.go, runner/types.go
- adds `--output-failures-only` flag
Fixes #81.
=> feat: only output failed tests

README.md, check/base.go, cmd/run.go, runner/run.go, runner/types.go, waflog/read.go, waflog/read_test.go, waflog/waflog.go
Look back an additional line and do not assume that the marker will appear on the last line. httpd will write the 404 error **after** the ModSecurity output (depending on the log level).
This commit also fixes some casing issues that might occur, especially in case of tests.
Fixes #104.
=> fix: look more than one line for log markers

runner/run.go
Hi there, another small nit. [Updating go-ftw used inside Coraza](https://github.com/corazawaf/coraza/pull/516) I found this comment that may be misleading.
```
// Run runs your tests with the specified Config. Returns error if some test failed
```
It seems that errors are returned when problems happen when testing, and are not related to failed tests.
E.g.: Here failed tests are still printed during  `os.Exit` not when the `err` is checked:
https://github.com/coreruleset/go-ftw/blob/acafe99202eeecebbf57f26c9827d6f169067194/cmd/run.go#L74-L78
Am I missing something? Otherwise, I'm just removing the second part of the comment. 
Thank you!
=> chore: removes a misleading comment

cmd/run.go, go.sum, output/output.go, output/output_test.go, runner/run.go, runner/stats.go
After running a couple of plugin tests, I realized that if some error was badly propagated, stats were created with `nil`, but at the `os.Exit` we were calling the stats, hence getting a fault.
Now this PR makes two changes:
- create Stats as empty lists instead of nil
- propagate errors so it can be shown at the cmd level
=> fix: create empty lists in stats

check/base.go, check/base_test.go, check/error_test.go, check/logs_test.go, check/response_test.go, check/status_test.go, cmd/root.go, cmd/run.go, config/config.go, config/config_test.go, config/types.go, runner/run.go, runner/run_test.go, runner/types.go, waflog/read.go, waflog/read_test.go, waflog/types.go, waflog/waflog.go, waflog/waflog_test.go
Removes global config. Now some methods will receive the extra config parameter.
Partially addresses #108.
=> feat: move config to parameter instead of global

cmd/root.go, cmd/run.go
The global variable holding the configuration was shadowed in the method that loades the configuration file. Hence, the configuration file was never applied.
=> Properly load config file

output/output.go, runner/stats.go
Hello!
I'm experiencing some (graphically) bad outputs running go-ftw on an enhanced terminal. It is about some message keys that are not matching the `normalCatalog` values. Proposing some small changes.
Before:
```
🚀 Running go-ftw!
👉 executing tests in file 911100.yaml
running 911100-1:
running 911100-2:
running 911100-3:
running 911100-4: ✔ passed in 51.387459ms (RTT 97.476958ms)
running 911100-5:
running 911100-6: 💥 failed in 5.2525ms (RTT 52.799084ms)
running 911100-7: 💥 failed in 5.80375ms (RTT 53.880125ms)
running 911100-8: 💥 failed in 4.340666ms (RTT 52.446125ms)
skipping 920250-1 - (enabled: false) in file.
skipping 920250-2 - (enabled: false) in file.
skipping 920250-3 - (enabled: false) in file.
skipping 920360-1 - (enabled: false) in file.
skipping 920370-1 - (enabled: false) …
```
=> chore: fix some messages catalog correspondences

ftwhttp/header.go, ftwhttp/request.go, ftwhttp/request_test.go
Fixed: https://github.com/coreruleset/go-ftw/issues/134
CRS 942101-* tests received "411 Length Required" data. go-ftw sends Content-Length header if request data is not 0 byte for now.
https://github.com/coreruleset/go-ftw/blob/main/ftwhttp/header.go#L78-L80
I think the Content-Length header needed if request header's method is "POST".
=> fix: send Content-Length header if there is payload

check/logs.go, check/response.go, check/status.go, runner/run.go, runner/run_test.go
Hi, I took a quick look at https://github.com/coreruleset/go-ftw/issues/137. As far as I understand, currently `checkResult` as soon as an assertion is true, returns `Success`, considering the rule as passed. This PR proposes to invert the logic, making sure that all the required assertions are not failing.
Not sure about these added `XRequired()` methods, maybe that could be merged into the `XAssert()` methods, but then it does not really become just an "assertion".
Feel free to close it if you have any better implementation in mind!
=> fix: checkResult now matches all outputs required in the rule

README.md, config/config_test.go, config/types.go, runner/run.go, runner/run_test.go, test/types.go
The feature added in https://github.com/coreruleset/go-ftw/pull/63 replaces the empty host field with the destination address. It has conflicts with some CRS test that are trying to send on purpose empty or missing host headers.
It happens only when `dest_addr` override is in place, for this reason CRS tests against apache are still running smoothly.
This PR implements @theseion [idea](https://github.com/coreruleset/go-ftw/issues/129#issuecomment-1421347248), adding the `override_empty_host_header` flag that enables this feature, permitting, by default, to keep running CRS tests as intended. 
More context in the issue: https://github.com/coreruleset/go-ftw/issues/129.
Thanks the feedbacks!
tentatively closes https://github.com/coreruleset/go-ftw/issues/129
=> feat(config): adds override_empty_host_header flag

README.md, runner/run.go, runner/run_test.go, test/defaults_test.go, test/types.go
Follows https://github.com/coreruleset/go-ftw/pull/132#discussion_r1150838288, extends override capabilities implementing the remaining override elements.
=> chore: implements remaining overrides

check/base_test.go, check/error_test.go, check/logs_test.go, check/response_test.go, check/status_test.go, cmd/check_test.go, cmd/root_test.go, cmd/run_test.go, config/config_test.go, ftwhttp/client_test.go, ftwhttp/connection_test.go, ftwhttp/header_test.go, ftwhttp/request_test.go, ftwhttp/response_test.go, output/output_test.go, runner/run_cloud_test.go, runner/run_input_override_test.go, runner/run_test.go, test/data_test.go, utils/tests_test.go, waflog/read_test.go, waflog/waflog_test.go
The testify test suite offers a `Required()` context that will fail immediately on failure. For `NoError()` we want assertions to always fail immediately because continuing doesn't make sense and just spams the log.
=> feat: fail tests immediately if `NoError()` fails

README.md, check/base.go, check/base_test.go, check/error.go, cmd/root.go, config/config.go, ftwhttp/types.go, runner/run.go, runner/run_input_override_test.go, runner/run_test.go, test/data_test.go, test/defaults_test.go, test/files.go, test/files_test.go, test/types.go, test/types_test.go, test/yaml.go
StopMagic is still supported for backwards compatibility.
=> feat!: replace StopMagic with autocompleteHeaders

ftwhttp/header.go
Multiple log entries are produced for each test, for each HTTP header written.
=> fix: reduce log level when writing headers

runner/run.go, runner/run_test.go
When the logic was inverted, as we renamed `stop_magic` to `autocomplete_headers`, we forgot to remove the logic inversion when passing the option to the request builder.
=> fix: no longer negate `autocomplete_headers` option

runner/run.go
Not sure if I'm using and testing the runner package correctly or not, but since `expectedOutput.ExpectError` is a pointer to boolean, dereferencing it is inherently unsafe and panic-able and depending on the behavior and outputs of go-ftw tests yaml deserialization, logically, it could panic in some cases and I believe this small change makes it a bit safer.
If I'm missing any point here, I'd appreciate your clarifying it.
Thanks.
=> fix runner expected-error check potential panic

renovate.json
goccy/go-yaml still has a performance issue in versions > v1.9.2.
=> chore: make MendRenovate ignore updates to go-yaml

.github/workflows/codeql.yml
The CodeQL workflow is currently not being run and it is not clear why. Try renaming the workflow to force GH to run it.
=> chore: rename codeql workflow

.pre-commit-config.yaml, check/base.go, check/base_test.go, check/logs.go, check/logs_test.go, check/status_test.go, config/types.go, ftwhttp/client.go, ftwhttp/client_test.go, go.sum, runner/run.go, runner/stats.go, test/defaults.go, test/types.go, waflog/read.go, waflog/read_test.go, waflog/types.go, waflog/waflog.go, waflog/waflog_test.go
The implementation for positive match of a list of IDs only required a single ID to match instead of all.
This commit also introduces memoization to minimize IO when searching the log.
Also fixed pre-commit config.
=> fix: properly handle multiple IDs in positive log match

runner/run.go, runner/run_test.go, runner/testdata/TestIgnoredTestsRun.yaml
Overridden results were added to the stats twice: once by the overridden logic that was correctly setting them as overridden tests, and once by `RunTest` that was adding the overridden test using the result of the previous run.
Bumped into the following output where `920290-1` was displayed as both an ignored and failed. 
```
--- FAIL: TestFTW (14.27s)
coreruleset_test.go:284: 7 ignored tests: [920100-5 920100-8 920270-4 920290-1 920290-4 920430-8 930110-7]
coreruleset_test.go:288: 8 failed tests: [920274-1 920280-3 920290-1 920430-3 920430-5 920430-9 920610-2 920620-1]
```
When an overridden test was detected in `RunStage`, the result addition was not delegated to the `RunTest` function, but directly called there (`addResultToStats`). Once returned, `addResultToStats` was executed once …
=> fix: overridden tests displayed as failing

check/base.go, check/logs_test.go, cmd/check_test.go, cmd/run_test.go, config/config_test.go, runner/run.go, runner/run_cloud_test.go, runner/run_test.go
This fixes all broken tests and RunTest/FTWCheck on windows, by properly closing opened files.
Windows refuses to delete files as long as a file descriptor is open. Closing the temporary files in the tests and closing the log files opened by FTWCheck in RunTest fixes these issues.
Closes  #349
=> fix: broken tests and RunTest on windows

.github/workflows/test.yml
This should run the github actions for testing the code for both linux and windows.
This should be merged after https://github.com/coreruleset/go-ftw/pull/348
See #349
=> feat: add PR checks for windows

test/types.go, waflog/read.go
Nits about logs printed at debug/trace levels. It helps a bit more understanding the logs when strings are empty, or with whitespace chars. I would even go with `%q`, but I kept the single quotes format present in other logs.
=> chore: adds single quote boundaries when printing strings in logs

go.mod, go.sum, renovate.json
This PR proposes downgrading the Go version to `v1.22`, following the recent bump from `v1.21` to `v1.23` happened in https://github.com/coreruleset/go-ftw/pull/369. This because:
- It doesn't appear to be an immediate need for `v1.23` (I'm thinking about new features or dependencies requiring it).
- It would allow projects importing go-ftw more time to upgrade to the most recent Go version, still allowing them to adopt recent go-ftw versions in the meantime. For example, Coraza follows a policy of supporting the last two Go releases, so the adoption of newer go-ftw versions would slow down.
- Why `v1.22` and not back to `v1.21`? No strong opinion here:
- It would still upgrade the go version, just more gradually. 
- It would align with the go version we have in `crs-toolchain` (I guess …
=> chore: set min go version to `v1.22`

cmd/quantitative.go, internal/quantitative/local_engine.go, internal/quantitative/local_engine_test.go, internal/quantitative/runner.go, internal/quantitative/runner_test.go
- Adds `q` as `quantitative` alias
- Runs quantitative testing with `DetectionOnly`: detection is not interrupted anymore if phase 1 rules match.
- code Refactor to better fit providing the `--payload` parameter
- Fixes `--payload`
=> quantitative: runs with `DetectionOnly`, fixes `--payload`

cmd/quantitative.go, internal/quantitative/runner.go
- create the file if it doesn't exist
- the file doesn't need to exist beforehand
=> fix: create output file if it does not exist

ftwhttp/connection.go, ftwhttp/request.go
I'm aiming to import the ftwhttp package into another Go project and call the `buildRequest` function directly. However, since `buildRequest` is unexported (lowercased), it’s inaccessible from outside the package.
Renaming `buildRequest` to `BuildRequest` would make it an exported function, allowing me to use it outside of go-ftw
=> feat: rename `buildRequest` to `BuildRequest` to make it exported

waflog/read.go, waflog/read_test.go
Address https://github.com/coreruleset/coreruleset/issues/3239.
This PR proposes to extend the regex looking for IDs to support also IDs coming with escaped quotes.
JSON log lines such as the following one are not supported:
```
{"time":"2024-12-06T11:13:12.250069+01:00","level":"ERROR","msg":"[client \"127.0.0.1\"] Coraza: Warning. Request content type charset is not allowed by policy [file \"@owasp_crs/REQUEST-920-PROTOCOL-ENFORCEMENT.conf\"] [line \"2753\"] [id \"920480\"] [rev \"\"] [msg \"Request content type charset is not allowed by policy\"] [data \"|garbage|\"] [severity \"critical\"] [ver \"OWASP_CRS/4.7.0\"] [maturity \"0\"] [accuracy \"0\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-protocol\"] [tag \"paranoia-level/1\"] [tag …
```
=> Extend ID Regex to support escaped quotes

README.md, cmd/quantitative.go, cmd/root.go, cmd/run.go, cmd/run_test.go
=> fix: use correct names for flags

README.md, cmd/version.go, config/types.go, ftwhttp/request.go, ftwhttp/request_test.go, ftwhttp/types.go, runner/run.go, runner/run_input_override_test.go, runner/run_test.go, test/defaults.go, test/defaults_test.go, test/types.go
- remove raw input references in code
- cleanup
- Fixes #408
=> chore: remove raw input references

runner/run.go, runner/run_test.go, test/data.go, test/data_test.go
`encoded_data` has been part of the spec for a while but never implemented. Allows passing body data base64 encoded for complex bodies.
Refs #428
=> feat: implement `encoded_data`

test/types.go, test/types_test.go
`[no_]log_contains` was deprecated but not removed. During the refactoring to `[no_]expect_ids` / `[no_]match_regex` using the old values was accidentally dropped.
Refs #428
=> fix: use legacy `[no_]log_contains` if set

waflog/read.go, waflog/read_test.go
- use two separate regular expressions to find rule IDs, one for the standard log format, and one for JSON as fallback
- be stricter about the format, especially for IDs in JSON
Fixes #435
=> fix: improve rule ID detection

ftwhttp/header.go, ftwhttp/request_test.go
=> fix: tolerate tests that do not specify any headers

README.md, check/base.go, check/logs_test.go, runner/run.go, waflog/read.go, waflog/read_test.go
I'm investigating some flakiness and found that the same marker might be retrieved for both the starter and the final one. When this happens, the function responsible for retrieving all the marked lines can not locate the starter marker. As a result, it uses all the logs up to the beginning of the file and processes IDs from lines belonging to previous tests, leading to incorrect results. 
My idea is that it can happen when go-ftw is too fast and reads again the same line before the engine/connector manages to write/flush the new logs (which include the final marker) into the file.
From a visual perspective (_Note: The read is performed backward._):
**] Expected scenario:**
start marker: `8888-8888`
final marker: `9999-9999`
```
...
log id:10
8888-8888
log id:11
9999-9999
```
1) We look …
=> fix: flaky results: same start and end marker

.github/workflows/test.yml
The self-updater tests make API requests to GitHub and can run into a rate limit if they are not authenticated.
=> chore: expose GitHub token for API requests from tests

README.md, cmd/run.go, cmd/run_test.go, config/config.go, config/runner_config.go, config/types.go, ftwhttp/client.go, ftwhttp/client_test.go, ftwhttp/response_test.go, ftwhttp/types.go, runner/check_base.go, runner/check_logs_test.go, runner/run.go, runner/run_test.go, waflog/waflog.go
We had a CLI flag for wait4x to disable TLS verification but no such option for the HTTP client.
This change replaces the specific flag for wait4x with a global flag `skip-tls-verification`, that configures both wait4x and the HTTP client.
Fixes #503
=> feat: implement skipping TLS verification
